### ISSUE TITLE
Spa - Flash Notifications

### ISSUE THREAD

**Issue by seanwash** [WatchNature/watchnature_app#10]
## Todo

- [x] Create notification reducer
- [x] Create notification container component
- [x] Create notification component
- [x] Apply bg color based on notification type
- [x] Dismiss notification on click
- [x] Dismiss notification after `dismissAfter` duration
