### ISSUE TITLE
Add Description to New Observation

### ISSUE THREAD

**Issue by bradyswenson** [WatchNature/watchnature_app#15]

**Comment by bradyswenson** [comment]
[Invision screen](https://projects.invisionapp.com/d/main#/console/8240421/230891847/preview)

![image](https://cloud.githubusercontent.com/assets/3144456/26701212/d09fa0b6-46e5-11e7-92ee-3bcdb6d4abb5.png)

![image](https://cloud.githubusercontent.com/assets/3144456/26701244/e996cc20-46e5-11e7-941b-393f748ae9e1.png)

**Comment by seanwash** [comment]
## Todo

- [x] Create an Observation Flow™ wrapper
- [x] Setup draft state for vuex
- [x] Setup save actions for vuex once draft has been filled & validated

## Create Flow

- A "new" action dispatches a request to the API that creates a new observation draft
- Client receives draft & stores into redux, `observations.draft`
- Client operates on local state forms until user commits each step to `observations.draft`
- Once the draft has been validated, a "share" button is available to the user which updates the draft
