### ISSUE TITLE
Add Tags to New Observation

### ISSUE THREAD

**Issue by bradyswenson** [WatchNature/watchnature_app#18]

**Comment by seanwash** [comment]
## Todo

- [x] Create tag schema
- [x] Create tag controllers (api/tags [index, show])
- [x] Add `ObservationTag` join table & adjust schemas
- [x] Add seed tags
- [x] Update observation changeset to cast_assoc for Tag_ids
- [x] Add tag module to Vuex
- [x] Add tag form to post wizard
- [x] Reorganize data so that forms operate on `post.observation`

---

Hey @bradyswenson,

Just a quick question about tagging - Based on the screenshot here https://cl.ly/lEIr, are tags broken up into smaller categories in the backend?

It doesn't look like (to me anyway) that we would need to add another table for categories, maybe we could add a field onto Tag that would contain a type of tag? Ex:

```
Tags
---
name: bird
type: general
---
name: feeding
type: behavior
---
...
```

We could just use enumerators for the type, and this way it would allow us to format the display of tags like in the mockup.

**Comment by seanwash** [comment]
Note: Handled IRL

**Comment by seanwash** [comment]
@bradyswenson on this screen, how does a user know which tags have been selected?

https://cl.ly/lI86

**Comment by seanwash** [comment]
@bradyswenson How about something like this?

https://cl.ly/lHku

-- Edit

Im so sorry, that's twice in a row I've forgotten to attach the gif.

**Comment by seanwash** [comment]
@bradyswenson 💯  just added some tags to an observation and saved it. I also just changed up how things work, so now we can make one post request to the API, and it will create both a post and the observation at the same time!

**Comment by seanwash** [comment]
@bradyswenson I also just tossed in a search input for searching available tags. The matching I think is a bit too loose, but we can tune that up later! For now we're storing all of the tags into Vuex and searching on the client side since it's instantaneous. Once we start to get a lot of tags, we can move that to API calls if needed.

Here's a quick gif of that: https://cl.ly/lKZP

**Comment by seanwash** [comment]
Closing for now, as we get further along we can open new issues for design updates or tweaks.
