### ISSUE TITLE
Signin user on signup

### ISSUE THREAD

**Issue by seanwash** [WatchNature/watchnature_app#25]
## Todo

- [ ] authenticate user on create
- [ ] add the new user's token to the user create api response
- [ ] Update `Signup.vue.signup()` to store the user and token data (like `Signin.vue`)
- [ ] Maybe move this to an action in Vuex?
