### ISSUE TITLE
User Roles [Phase 2]

### ISSUE THREAD

**Issue by seanwash** [WatchNature/watchnature_app#45]
### Phase 1
```
Accounts.User (pre-existing)
- many to many Accounts.Group

Accounts.UserGroup (join)
- user_id
- group_id

Accounts.Group
- name:string
```
### Phase 2
```
Accounts.Permission
- action:string (vuex/redux style? table_name_action_name)

Accounts.Group (pre-existing)
- has_many Accounts.Permission
```

## Todo

- [x] Add accounts namespace
- [x] Shore up policies surrounding post creation, deletion, etc
    - [x] User Update - admins or own user
    - [x] User Delete - admins
    - [x] Observation Delete - admins
- [x] Add Group schema and migration
- [x] Move user creation from controller to Accounts context
