### ISSUE TITLE
Comments & polymorphic relationships with Ecto

### ISSUE THREAD

**Issue by seanwash** [WatchNature/watchnature_app#5]
## Resources

* https://elixirforum.com/search?q=polymorphic
* https://hexdocs.pm/ecto/Ecto.Schema.html#many_to_many/3
* http://stackoverflow.com/questions/922184/why-can-you-not-have-a-foreign-key-in-a-polymorphic-association
* https://hexdocs.pm/ecto/Ecto.Schema.html#belongs_to/3-polymorphic-associations

## Proposal

I propose that we use option three as outlined in the [poly assoc docs](https://hexdocs.pm/ecto/Ecto.Schema.html#belongs_to/3-polymorphic-associations). Basically, we'll just have a join table for each schema that has many comments, like:

```
Post, Comment | posts_comments -> user_id, post_id
Observation, Comment | observations_comments -> user_id, observation_id
```

It's simple, predictable, and explicit. What do you think @bradyswenson?

## Considerations

How should we handled threaded comments down the road? Maybe abstract it out to a `Thread` schema?

## Todo

* [x] Comment CRD
* [x] Scope get actions to comments by post id
* [x] Authorize comment update & delete to comment owner
* [x] Verify comments can't be created by guests
