### ISSUE TITLE
Image Uploads

### ISSUE THREAD

**Issue by seanwash** [WatchNature/watchnature_app#7]
## Todo

* [x] Setup new S3 || Cloudinary account for WN
* [x] Create ObservationImage schema
    * For Arc `observation_id:references:observaton image:avatar`
    * For Cloudinary `observation_id:references:observation cloud_public_id:string  cloud_url:string cloud_secure_url:string`
* [x] Add image to Observations
* [x] Auto assign observation_id on create
* [x] Authorize that users can only create/delete images that belong to observations that they own

## Adding Images to an observation

1. User adds new observation
2. User chooses to add an image to an observation
3. On image select, initiate cloudex upload, create an ObservationImage on success
4. Update view with new ObservationImage.url

## Resources

* https://github.com/smeevil/cloudex

## Coudinary

Hidden small plan https://cloudinary.com/users/upgrade/small

**Comment by seanwash** [comment]
@bradyswenson I linked up that hidden small plan that I found. We should probably keep that in mind!
