### ISSUE TITLE
User liking content

### ISSUE THREAD

**Issue by seanwash** [WatchNature/watchnature_app#72]
## Todo

```
Observation
- like_count [new column, integer, counter cache, updated via Reaction.add_like with Ecto.Multi]
- has_many ObservationLikes

ObservationLike
- belongs_to User
- Belongs_to Post

Reaction Context

Reaction.add_like(user, entity_type) - Pattern match on the entity type and apply join record
```

- [x] Make up a new context representing comments and likes (Interactions?)
- [x] Add API endpoints for users to like content (current_user)
- [x] Double check like deletion permissons
- [x] Controller tests for likes
- [x] Adjust stream list functions to take a current_user param and preload associations there
- [x] Add unique constraints btwn observation and user
