### ISSUE TITLE
Reactions - Observation Comments

### ISSUE THREAD

**Issue by seanwash** [WatchNature/watchnature_app#76]
## Todo

- [ ] Remove previously existing comments table in favor of observation_comments
- [ ] Remove old comment controller
- [ ] Remove old comment policy
- [ ] Create observation_comments schema and migration
- [ ] Create observations_comments controller
- [ ] Create observations_comments policy
