### ISSUE TITLE
SPA

### ISSUE THREAD

**Issue by seanwash** [WatchNature/watchnature_app#8]
## Todo

* [x] React Router
* [x] Redux?

### Global Things

* [x] Flash Messages

### Signup/Authentication

- [x] Signup Form
- [x] Login Form
- [x] Use cookie.js to store session state?
- [ ] Sign In/Sign Out
    - [ ] Sign up notification "Thanks! You can now sign in"
    - [ ] Sign in notification "Welcome Back"
    - [x] Add quick sign in/out links to header
    - [x] persist user authenticated state via stored cookie
    - [x] Redux things for sign in
    - [x] Redux things for sign out
- [ ] Send auth token with all signed in ajax requests
- [ ] Move API requests to some sort of API wrapper
